repo: Update linting to fix broken checks
linting pipeline is forcibly downgrading flake8 version and causing
failures with AttributeError: 'EntryPoints' object has no attribute 'get'
Update linting to be in line with what the pipeline image is running

Change-Id: I740c339468704c3a7f68606167d4ccabc2a3bf2b